# Generated by Django 2.2.2 on 2019-07-21 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zzikplace', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
