# Generated by Django 2.2.2 on 2019-07-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzikplace', '0003_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='x',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='place',
            name='y',
            field=models.FloatField(default=None),
        ),
    ]
