# Generated by Django 2.2.1 on 2019-07-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzikplace', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchword', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
