# Generated by Django 2.1.7 on 2019-08-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zzikplace', '0005_auto_20190805_0847'),
        ('zzikplace', '0004_searchword'),
    ]

    operations = [
    ]
