# Generated by Django 2.2.3 on 2019-08-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zzikplace', '0006_merge_20190807_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchWord',
        ),
    ]
