# Generated by Django 2.1.7 on 2019-08-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzikplace', '0007_delete_searchword'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
