# Generated by Django 2.2.1 on 2019-08-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zzikplace', '0003_searchword'),
        ('zzikplace', '0008_place_place_hit'),
    ]

    operations = [
    ]
