# Generated by Django 2.1.7 on 2019-08-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzikplace', '0009_merge_20190809_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tag_content',
            field=models.TextField(blank=True),
        ),
    ]
